services:
  qgis-desktop:
    build: .

    volumes:
      - .:/code
    environment:
      - DISPLAY=unix${DISPLAY}
      - QT_QPA_PLATFORM=offscreen
      - XDG_RUNTIME_DIR=/tmp/runtime-root
    cap_add:
      - SYS_PTRACE
